[package]
name = "russh-padding-distribution-analyzer"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rand_distr = "0.2"
