[package]
name = "russh-definitions"
version = "0.1.0"
license = "MIT/Apache-2.0"
keywords = ["ssh", "network", "russh"]
edition = "2021"

[dependencies]
num-bigint = "0.4"
rand = "0.7"
thiserror = "1.0"
