[package]
name = "russh-common"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["ssh", "network", "russh"]
edition = "2018"

[dependencies]
nom = "6.2"
num-bigint = "0.2"
rand = "0.7"
err-derive = "0.3"

[dev-dependencies]
matches = "0.1"
